apiVersion: v1
kind: Pod
metadata:
  name: ldap-pod
  labels:
    app: ldap
spec:
  containers:
    - name: contenedor-ldap
      image: osixia/openldap:latest
      env:
        - name: LDAP_ORGANISATION
          value: "Daniel S.A"
        - name: LDAP_DOMAIN
          value: "daniel.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
      ports:
        - containerPort: 389
        - containerPort: 636
      volumeMounts:
        - name: ldap-ldif
          mountPath: /container/service/slapd/assets/config/bootstrap/ldif
          readOnly: true
  volumes:
    - name: ldap-ldif
      configMap:
        name: ldap-bootstrap-ldif
  imagePullSecrets:
    - name: ecr-secret
