apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/web-pv" # Crear ruta en el nodo de minikube