apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: ldap-crear-usuarios
        image: osixia/openldap:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            PASS1=$(slappasswd -s "password1");
            PASS2=$(slappasswd -s "password2");
            mkdir -p /ldif;
            printf "dn: ou=users,dc=daniel,dc=com\nobjectClass: organizationalUnit\nou: users\n\n" > /ldif/00-ou-users.ldif;
            printf "dn: uid=user1,ou=users,dc=daniel,dc=com\nobjectClass: inetOrgPerson\nobjectClass: posixAccount\nobjectClass: top\ncn: User One\nsn: One\nuid: user1\nuidNumber: 1001\ngidNumber: 1001\nhomeDirectory: /home/user1\nloginShell: /bin/bash\nuserPassword: %s\n\n" "$PASS1" > /ldif/10-user1.ldif;
            printf "dn: uid=user2,ou=users,dc=daniel,dc=com\nobjectClass: inetOrgPerson\nobjectClass: posixAccount\nobjectClass: top\ncn: User Two\nsn: Two\nuid: user2\nuidNumber: 1002\ngidNumber: 1002\nhomeDirectory: /home/user2\nloginShell: /bin/bash\nuserPassword: %s\n\n" "$PASS2" > /ldif/20-user2.ldif;
            chmod 644 /ldif/*.ldif;
        volumeMounts:
        - name: ldap-init
          mountPath: /ldif

      containers:
      - name: contenedor-nginx
        image: 887465598388.dkr.ecr.us-east-1.amazonaws.com/nginx-rockylinux:version1
        imagePullPolicy: Always
        ports:
        - containerPort: 443

      - name: contenedor-ldap
        image: osixia/openldap:latest
        env:
        - name: LDAP_ORGANISATION
          value: "Daniel S.A"
        - name: LDAP_DOMAIN
          value: "daniel.com"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
        ports:
        - containerPort: 389
        - containerPort: 636
        volumeMounts:
        - name: ldap-init
          mountPath: /custom-ldif
        lifecycle:
          postStart:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - |
                cp -r /custom-ldif/* /container/service/slapd/assets/config/bootstrap/ldif/custom/
      volumes:
      - name: ldap-init
        emptyDir: {}
      imagePullSecrets:
      - name: ecr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ldap-service
spec:
  selector:
    app: nginx
  ports:
    - name: ldap-tcp
      protocol: TCP
      port: 389
      targetPort: 389
    - name: ldap-tls
      protocol: TCP
      port: 636
      targetPort: 636

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 443         # Puerto del servicio
      targetPort: 443    # Puerto del contenedor Nginx
      nodePort: 32000   # Puerto externo en los nodos