apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx
    service: web
spec:
  containers:
    - name: contenedor-nginx
      image: dramlin1010/nginx-rockylinux
      imagePullPolicy: Always
      stdin: true
      tty: true
      ports:
        - containerPort: 80
        - containerPort: 443
      command: ["/bin/bash"]
