---
- name: Desplegar Nginx en Docker
  hosts: ["192.168.52.2"]
  become: yes
  vars_files:
    - nginx_vars.yml
  tasks:
    - name: Asegurar servicio Docker activo
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ejecutar contenedor base
      ansible.builtin.command:
        cmd: >
          docker run -d -it -p 443:443 -p 80:80
          --name {{ container_name }}
          -v /home/usuario/docker-web/nginx/certs:/etc/nginx/certs
          -v /home/usuario/docker-web/nginx/conf.d:/etc/nginx/conf.d
          rockylinux:9 /bin/bash

    - name: Actualizar paquetes en el contenedor
      ansible.builtin.command:
        cmd: docker exec -it {{ container_name }} dnf update -y --setopt=sslverify=false

    - name: Instalar NGINX en el contenedor
      ansible.builtin.command:
        cmd: docker exec -it {{ container_name }} dnf install nginx -y --setopt=sslverify=false

    - name: Arrancando Nginx en el contenedor
      ansible.builtin.command:
        cmd: docker exec -it {{ container_name }} nginx

    - name: Crear imagen desde contenedor
      command: docker commit {{ container_name }} {{ dockerhub_repo }}:{{ docker_image_tag }}

    - name: Autenticar en Docker Hub
      command: docker login -u {{ dockerhub_user }} -p {{ dockerhub_pass }}

    - name: Subir imagen a Docker Hub
      command: docker push {{ dockerhub_repo }}:{{ docker_image_tag }}
