apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
spec:
  storageClassName: efs-sc
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07ca9be00349a60ac