name: EKS Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Escribe 'yes' para confirmar la destrucción"
        required: true
        default: "no"

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name mieks --region us-east-1

      - name: Confirm destruction
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }}
        run: |
          echo "Destrucción no confirmada. Por favor, escribe 'yes' para confirmar."
          exit 1

      # Eliminar aplicaciones web
      - name: Delete Nginx
        run: kubectl delete -f eks_nodo/deployment_pod_nginx.yml

      - name: Delete Charneco
        run: kubectl delete -f eks_nodo/deployment_pod_charneco.yml

      - name: Delete Apache
        run: kubectl delete -f eks_nodo/deployment_pod_apache.yml

      # Eliminar servicios
      - name: Delete Services
        run: kubectl delete -f eks_nodo/services.yml

      # Eliminar PHP-FPM y LDAP
      - name: Delete LDAP
        run: kubectl delete -f eks_nodo/deployment_pod_ldap.yml

      - name: Delete PHP-FPM
        run: kubectl delete -f eks_nodo/php-fpm-deployment.yml

      # Eliminar StorageClass, PV y PVC
      - name: Delete PVC
        run: kubectl delete -f eks_nodo/pvc.yml

      - name: Delete PV
        run: kubectl delete -f eks_nodo/pv.yml

      - name: Delete StorageClass
        run: kubectl delete -f eks_nodo/storageclass-efs.yml

      # Eliminar el driver EFS CSI
      - name: Delete EFS CSI driver
        run: |
          kubectl delete -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.5"
          kubectl get pods -n kube-system

      - name: Verify resources deletion
        run: kubectl get all
