name: EKS Git

on:
  push:
    branches:
      - Kubernetes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name mieks --region us-east-1

      # Instalar el driver EFS CSI
      - name: Install EFS CSI driver
        run: |
          kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.5"
          sleep 2
          kubectl get pods -n kube-system

      # Aplicar StorageClass, PV y PVC
      - name: Apply StorageClass, PV, and PVC
        run: |
          kubectl apply -f eks_nodo/storageclass-efs.yml
          sleep 1  # Esperar 1 segundo
          kubectl apply -f eks_nodo/pv.yml
          sleep 1  # Esperar 1 segundo
          kubectl apply -f eks_nodo/pvc.yml
          sleep 1  # Esperar 1 segundo

      # Desplegar PHP-FPM, LDAP y servicios
      - name: Deploy PHP-FPM
        run: kubectl apply -f eks_nodo/php-fpm-deployment.yml

      - name: Wait for PHP-FPM
        run: sleep 5  # Esperar 5 segundos

      - name: Deploy LDAP
        run: kubectl apply -f eks_nodo/deployment_pod_ldap.yml

      - name: Wait for LDAP
        run: sleep 5  # Esperar 5 segundos

      - name: Deploy Services
        run: kubectl apply -f eks_nodo/services.yml

      - name: Wait for Services
        run: sleep 3  # Esperar 3 segundos

      # Desplegar aplicaciones web
      - name: Deploy Apache
        run: kubectl apply -f eks_nodo/deployment_pod_apache.yml

      - name: Wait for Apache
        run: sleep 8  # Esperar 8 segundos

      - name: Deploy Charneco
        run: kubectl apply -f eks_nodo/deployment_pod_charneco.yml

      - name: Wait for Charneco
        run: sleep 8  # Esperar 8 segundos

      - name: Deploy Nginx
        run: kubectl apply -f eks_nodo/deployment_pod_nginx.yml

      - name: Wait for Nginx
        run: sleep 8  # Esperar 8 segundos

      # Verificar el estado de los recursos
      - name: Show Kubernetes resources
        run: kubectl get all
