name: Terraform AWS Deployment
on:
  push:
    branches:
      - VPC_Infra

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Instalar terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Init Terraform
        run: terraform init
        working-directory: terraform  # WorkDir Terraform donde estan los tf

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform

      - name: Subir terraform.tfstate a S3
        uses: aws-actions/s3-sync-action@v1
        with:
          source-dir: terraform/terraform.tfstate
          bucket: s3-test-daniel-bucket-lol
          destination-dir: terraform/ # Carpeta del S3
