name: Terraform AWS Deployment
on:
  push:
    branches:
      - VPC_Infra

jobs:
 terraform: # NOMBRE OPCIONAL
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Repository
     uses: actions/checkout@v4
   - name: Instalar Terraform
     uses: actions/setup-terraform@v3
   - name: Credenciales AWS
     uses: aws-actions/configure-aws-credentials@v4
     with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
       aws-region: us-east-1
   - name: init terraform
     run: terraform init
     working-directory: terraform

   - name: apply terraform
     run: terraform apply -auto-approve
     working-directory: terraform

   - name: upload terraform state
     uses: actions/upload-artifact@v4
     with:
      name: Artifact
      path: terraform/terraform.tfstate
